#!/bin/bash -e

DC="docker-compose -f docker-compose.builder.yml"

function finish() {
  # down and remove volumes
  $DC down --volumes
}

rm -f *.deb
$DC build

trap finish EXIT
$DC run --rm builder $@

if [ $# -eq 0 ] ; then
 $DC run --rm -T builder bash -c '(cd /app && tar cf - *.deb)' | tar xf -
fi
